[project]
name = "day17-track2-datapipeline-nhutrongthah-01977"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gnuthnaht14", email = "thanhnhutrong@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9,<2",
    "dbt-duckdb>=1.9,<2",
    "duckdb>=1.4,<2",
]

[project.scripts]
day17-track2-datapipeline-nhutrongthah-01977 = "day17_track2_datapipeline_nhutrongthah_01977:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
